### ISSUE TITLE
Convert EFI to OpenCore?

### ISSUE THREAD

**Issue by jball-98** [nguyenhung9x2018/HP-PROBOOK-4540S-HACKINTOSH#3]
Could you possibly update the efi to OpenCore?

This efi and clover is great but adding OpenCore instead would make it faster and more stable.

Thanks!

**Comment by nguyenhung9x2020** [comment]
Check branch new

**Comment by jball-98** [comment]
Thanks!

Also

- Audio works fine with applealc
- you seem to be missing quite a few kexts, does continuity features work? (i have 53 and yours only has 29?)
- What is iService? i have never heard of it
- Would you update this for big sur when it releases?

**Comment by nguyenhung9x2020** [comment]
> Thanks!
> 
> Also
> 
> * Audio works fine with applealc
> * you seem to be missing quite a few kexts, does continuity features work? (i have 53 and yours only has 29?)
> * What is iService? i have never heard of it
> * Would you update this for big sur when it releases?

Audio works good on update 05/09
