### ISSUE TITLE
unable to boot

### ISSUE THREAD

**Issue by jball-98** [nguyenhung9x2018/HP-PROBOOK-4540S-HACKINTOSH#5]
![7534BB66-B2EF-4BA6-A6F9-1B74D035715C](https://user-images.githubusercontent.com/34079485/92358573-d4d5f900-f128-11ea-8dc3-524f2a39fa0f.jpeg)

**Comment by nguyenhung9x2020** [comment]
Clear nvram , reset nvram . You from clover to opencore ?

**Comment by nguyenhung9x2020** [comment]
Download again , it boot good on device for me

**Comment by jball-98** [comment]
> Clear nvram , reset nvram . You from clover to opencore ?

Yes i replaced my clover EFI with this EFI.

This error shows when i select my ssd when boot with usb

I have same specs and on Catalina 10.15.6

**Comment by nguyenhung9x2020** [comment]
https://github.com/dortania/OpenCore-Install-Guide/tree/master/clover-conversion . Since use EFI opencore Cleaning the Clover Junk in macOS , Removing kexts from macOS(S/L/E and L/E)

**Comment by nguyenhung9x2020** [comment]
Use branch 10.15.6 for version 10.15.6

**Comment by nguyenhung9x2020** [comment]
Use bigsur branch 10.16 beta

**Comment by jball-98** [comment]
I commented on wrong branch but i'm using the 10.15.6 efi for my catalina.

error: mac os version: not yet set
Tried clover conversion guide but didnt fix

**Comment by nguyenhung9x2020** [comment]
I will update and release again . Please wait

**Comment by nguyenhung9x2020** [comment]
https://github.com/nguyenhung9x2018/HP-PROBOOK-4540S-HACKINTOSH/releases 

Try update new
