### ISSUE TITLE
Battery percentage stuck on 100%

### ISSUE THREAD

**Issue by jball-98** [nguyenhung9x2018/HP-PROBOOK-4540S-HACKINTOSH#6]
Battery percentage is stuck on 100% when disconnected from power. Also it says power adapter is still connected when removing power adapter.

**Comment by nguyenhung9x2020** [comment]
OK . I will update soon

**Comment by nguyenhung9x2020** [comment]
![Screen Shot 2020-09-11 at 21 33 47](https://user-images.githubusercontent.com/35420114/92938290-91f08a00-f476-11ea-841b-7a180b7e79fb.png)
![Screen Shot 2020-09-11 at 21 34 11](https://user-images.githubusercontent.com/35420114/92938317-99179800-f476-11ea-85bf-fbca2f658b26.png)

**Comment by nguyenhung9x2020** [comment]
Battert woring good in v4
